runtime: python27
api_version: 1
threadsafe: true

libraries:
  - name: jinja2
    version: latest
handlers:
  - url: /img
    static_dir: img
  - url: /css
    static_dir: css
    
  - url: /.*
    script: main.app
